version = 1

exclude_patterns = [  
  "assets/**",  
  "**/node_modules/",
  "*.js",  
  "*.md",  
  "*.html",
  "*.css"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]